version: '3.8'

services:
  web:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "5000:5000"
    depends_on:
      - db
      - redis
    environment:
      DATABASE_URL: "postgresql://root:admin@db:5432/my_db"
      REDIS_URL: "redis://redis:6379/0"
    networks:
      - backend

  db:
    image: postgres:latest
    environment:
      POSTGRES_DB: my_db
      POSTGRES_USER: ashwaq
      POSTGRES_PASSWORD: admin
    networks:
      - backend

  redis:
    image: "redis:alpine"
    ports:
      - "6379:6379"
    networks:
      - backend

networks:
  backend:
    driver: bridge
